### PR TITLE
 Setup a basic page for the webapp

### LINKED ISSUE #4: Setup a basic page for the webapp
Let's get started with creating a basic page and using the API, UI/UX modifications can be done as we proceed.

### PR DESCRIPTION
**Pull request by collinsnji**
Fixes #4 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have tested the changes locally and they are functional.
- [x] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [x] This pull request has a descriptive title. For example, `Added/Fixed {Feature/Bug}`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by anshumanv** [comment]
Looks neat ! @collinsnji 
What I'm doubtful about is if we need the `package-lock.json` to be added to the commits ?
I think that's a configuration file that's generated while building/running
What are your views on this @sneakycr0w ?

**Comment by deadbirdi** [comment]
You shouldn’t. The dependencies will be in package.json. 

Zachary E Sohovich
Full Stack Web Developer
https://sneakycr0w.com
zach@sneakycr0w.com

**Comment by anshumanv** [comment]
Right, exactly.
Apparently in this PR you have included `package-lock`. Please add another commit to remove it @collinsnji 😄
Also i think every other thing is in place, what say @sneakycr0w

**Comment by collinsnji** [comment]
Oh right. I did not noticed when I committed the `package-lock` file. I'll remove it

**Comment by anshumanv** [comment]
Thanks ! Actually i should've added that to .gitignore earlier 😅

**Review by anshumanv — APPROVED** [review]
👍

**Comment by collinsnji** [comment]
Haha yeah. One more thing, how will the webapp be hosted? Heroku?

**Comment by anshumanv** [comment]
I don't have any such preference, what are your preferences on this ?

**Comment by collinsnji** [comment]
I think Heroku will be best for this :) @sneakycr0w what do you think?

**Comment by anshumanv** [comment]
Right, heroku sounds good to me. Let's hear from @sneakycr0w

**Pull request merged**
